apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: test-container
      image: gcr.io/google-samples/node-hello:1.0
      envFrom: # cargar el entorno desde un fichero de configmap
      - configMapRef:
          name: datos-mysql2 # el configmap que hemos creado
  restartPolicy: Never
