apiVersion: v1
kind: Pod
metadata:
  name: ejemplo 
spec:
  containers:
    - name: ejemplo 
      image: acertijo138/web1 # imagen de dockerhub
  imagePullSecrets: # para pasar el secret que contiene las credenciales
    - name : midocker # el secret con las credenciales