apiVersion: batch/v1
kind: Job
metadata:
  name: job4
spec:
  template:
    spec:
      containers:
      - name: job1
        image: alpine   
        command: ["sh","-c"]
        args: ["cat/etc/puff.txt"]
      restartPolicy: Never
