apiVersion: v1
kind: LimitRange # tipo limite para alterar recursos
metadata:
  name: recursos
spec:
  limits:
  - default: # a nivel de pods quiero esto
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 0.5
    max: # a nivel de cluster quiero todo esto, hay que tener esto claro y tambien ser precavidos a la hora de implementar estas cosas.
      memory: 1Gi
      cpu: 4
    min:
      memory: 128Mi
      cpu: 0.5
    type: Container
