apiVersion: v1
kind: Secret
metadata:
  name: secreto2
type: Opaque
stringData: # con stringData buscamos que los valores que pasamos a continuacion, sean encriptados, nosotros no los encriptamos porque k8s se encarga de ello
  usuario2: 'usu2' # pedimos encriptar
  usu2-pass: 'password-usu2' # pedimos encriptar
