apiVersion: v1
kind: Secret
metadata:
  name: secreto1
type: Opaque
data: # cuando se coloca este data, los valors que se ven aca debajo, son valores que ya han sido encriptados con anterioridad y colocado su valor encriptado
  usuario1: dXN1MQ== # dato ya encriptado previamente
  usu1-pass: cGFzc3dvcmQtdXN1MQ== # dato ya encriptado previamente
