apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels: # las labels del servico deben ir tambien en el statefulset
    app: db 
    name: mongodb
spec:
  ports:
  - port: 27017
  clusterIP: None # este None es el indicativo de un servicio de tipo HeadLess y cuando se trabaja con statefulsets se debe colocar si o si.
  selector:
    app: db
    name: mongodb 
